name: abc_express_ontology
version: "1.0.0"
config-version: 2

profile: abc_express_redshift

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  source_systems:
    - antero
    - abc-talk
    - obl
    - cms

models:
  abc_express_ontology:
    staging:
      +schema: staging
      +materialized: view
    core:
      +schema: core
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
