entityType: Location
fields:
  - name: displayName
    type: string
    required: true
  - name: locationType
    type: string
    required: false
  - name: provinceName
    type: string
    required: false
  - name: kabKotaCode
    type: string
    required: false
  - name: bpsCode
    type: string
    required: false
  - name: status
    type: string
    required: false
  - name: externalRef
    type: string
    required: false
