/** Spec: products/intelligence-agent/tools/compliance/str-report-generator.ts | BigPlan Phase 0.4 */
export interface STRReportInput {
  readonly entityName: string;
  readonly entityId?: string;
  readonly reportDate?: string;
  readonly region?: string;
  readonly suspiciousActivity: string;
  readonly transactionSummary?: string;
  readonly riskIndicators?: readonly string[];
  readonly evidenceRefs?: readonly string[];
  readonly analystNotes?: string;
}

export interface STRReportOutput {
  readonly markdown: string;
  readonly reportId: string;
  readonly generatedAt: string;
  readonly region: string;
}

export class STRReportGenerator {
  generate(input: STRReportInput): STRReportOutput {
    if (!input.entityName.trim()) {
      throw new Error("STRReportGenerator requires entityName");
    }
    if (!input.suspiciousActivity.trim()) {
      throw new Error("STRReportGenerator requires suspiciousActivity");
    }

    const region = input.region?.trim() || "ID";
    const reportDate = input.reportDate?.trim() || new Date().toISOString().slice(0, 10);
    const reportId = `STR-${reportDate.replace(/-/g, "")}-${input.entityId ?? input.entityName.slice(0, 8).replace(/\s+/g, "-").toUpperCase()}`;

    const indicators = input.riskIndicators?.length
      ? input.riskIndicators.map((i) => `- ${i}`).join("\n")
      : "- (none listed)";

    const evidence = input.evidenceRefs?.length
      ? input.evidenceRefs.map((e) => `- ${e}`).join("\n")
      : "- (none listed)";

    const markdown = [
      `# Suspicious Transaction Report (STR)`,
      ``,
      `| Field | Value |`,
      `| --- | --- |`,
      `| Report ID | ${reportId} |`,
      `| Region | ${region} |`,
      `| Report Date | ${reportDate} |`,
      `| Subject Entity | ${input.entityName} |`,
      input.entityId ? `| Entity ID | ${input.entityId} |` : "",
      ``,
      `## Suspicious Activity Narrative`,
      ``,
      input.suspiciousActivity.trim(),
      ``,
      input.transactionSummary
        ? `## Transaction Summary\n\n${input.transactionSummary.trim()}\n`
        : "",
      `## Risk Indicators`,
      ``,
      indicators,
      ``,
      `## Evidence / Provenance References`,
      ``,
      evidence,
      ``,
      input.analystNotes ? `## Analyst Notes\n\n${input.analystNotes.trim()}\n` : "",
      `---`,
      `_Generated by Daemon Intelligence Agent STRReportGenerator (PPATK APU-PPT context)._`,
    ]
      .filter(Boolean)
      .join("\n");

    return {
      markdown,
      reportId,
      generatedAt: new Date().toISOString(),
      region,
    };
  }
}
