{{- if .Values.externalSecrets.enabled -}}
{{- range .Values.externalSecrets.remoteSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "platform-api.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
    {{- range .keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ printf "daemon/%s/platform-api/%s" $.Release.Namespace . }}
    {{- end }}
{{- end }}
{{- end }}
