{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "platform-api.fullname" . }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "platform-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .fromNamespaceLabel }}
      ports:
        {{- range .ports }}
        - port: {{ . }}
          protocol: TCP
        {{- end }}
    {{- end }}
  egress:
    # DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- range .Values.networkPolicy.egress }}
    - {{- if .toCidr }}
      to:
        - ipBlock:
            cidr: {{ .toCidr }}
      {{- else if .toNamespaceLabel }}
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .toNamespaceLabel }}
      {{- end }}
      ports:
        {{- range .ports }}
        - port: {{ . }}
          protocol: TCP
        {{- end }}
    {{- end }}
{{- end }}
