#!/usr/bin/env bash
# Phase 0: expose local Go services via Cloudflare quick tunnels and write .env.staging (gitignored).
# Prereqs: supabase start, make migrate, make seed, clickhouse+neo4j+minio up.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

log="${TMPDIR:-/tmp}/daemon-phase0-tunnel.log"
: >"$log"

wait_tunnel_url() {
  local f="$1"
  local i url
  for i in $(seq 1 45); do
    url="$(grep -oE 'https://[a-zA-Z0-9-]+\.trycloudflare\.com' "$f" 2>/dev/null | head -1 || true)"
    if [ -n "$url" ]; then
      echo "$url"
      return 0
    fi
    sleep 1
  done
  echo "phase0-staging-tunnel-env: timeout waiting for tunnel URL in $f" >&2
  return 1
}

start_tunnel() {
  local port="$1" name="$2"
  local out="${TMPDIR:-/tmp}/daemon-tunnel-${name}.log"
  : >"$out"
  cloudflared tunnel --url "http://127.0.0.1:${port}" >>"$out" 2>&1 &
  echo "$!" >>"${TMPDIR:-/tmp}/daemon-tunnel-pids.txt"
  wait_tunnel_url "$out"
}

echo "phase0-staging-tunnel-env: ensure minio + data plane"
docker compose -f infra/docker/docker-compose.yml up -d minio clickhouse neo4j 2>&1 | tee -a "$log"

echo "phase0-staging-tunnel-env: health check local services (start with: make run-platform-api & make run-ontology-service & make run-rules-engine)"
for port in 8080 8081 8083; do
  if ! curl -sf "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
    echo "phase0-staging-tunnel-env: http://127.0.0.1:${port}/health not ready — start Go services on host first" >&2
    echo "  export OIDC_REQUIRED=true OIDC_ISSUER=http://127.0.0.1:54331/auth/v1 DATABASE_URL=postgresql://daemon_runtime:daemon_runtime_local@127.0.0.1:54332/postgres?sslmode=disable" >&2
    echo "  make run-platform-api & make run-ontology-service & make run-rules-engine" >&2
    exit 1
  fi
done

: >"${TMPDIR:-/tmp}/daemon-tunnel-pids.txt"
echo "phase0-staging-tunnel-env: starting cloudflared quick tunnels"
PLATFORM_URL="$(start_tunnel 8080 platform)"
ONTOLOGY_URL="$(start_tunnel 8081 ontology)"
RULES_URL="$(start_tunnel 8083 rules)"
AUTH_URL="$(start_tunnel 54331 auth || true)"

cat >"$root/.env.staging" <<EOF
# Generated by scripts/phase0-staging-tunnel-env.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ) (non-localhost proof URLs)
# Cloudflare quick tunnels to host-run Go services; not production staging VM.

PLATFORM_API_URL=${PLATFORM_URL}
ONTOLOGY_SERVICE_URL=${ONTOLOGY_URL}
RULES_ENGINE_URL=${RULES_URL}
CASE_SERVICE_URL=http://127.0.0.1:8084
INGESTION_SERVICE_URL=http://127.0.0.1:8082

NEXT_PUBLIC_PLATFORM_API_URL=${PLATFORM_URL}
NEXT_PUBLIC_ONTOLOGY_URL=${ONTOLOGY_URL}

OIDC_ISSUER=${AUTH_URL:-http://127.0.0.1:54331/auth/v1}
SUPABASE_URL=${AUTH_URL:-http://127.0.0.1:54331}
OIDC_REQUIRED=true

DATABASE_URL=postgresql://daemon_runtime:daemon_runtime_local@127.0.0.1:54332/postgres?sslmode=disable
CLICKHOUSE_URL=http://127.0.0.1:8123
NEO4J_URI=bolt://127.0.0.1:7687

PHASE0_STRICT=1
EOF

echo "phase0-staging-tunnel-env: wrote .env.staging"
echo "  PLATFORM_API_URL=$PLATFORM_URL"
echo "  ONTOLOGY_SERVICE_URL=$ONTOLOGY_URL"
echo "  RULES_ENGINE_URL=$RULES_URL"
echo "  OIDC_ISSUER=${AUTH_URL:-http://127.0.0.1:54331/auth/v1}"
