-- Full public schema snapshot for ABC Express (run via Supabase MCP execute_sql)
SELECT json_build_object(
  'activity_logs', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.activity_logs t),
  'antero_sync_log', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.antero_sync_log t),
  'audit_logs', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.audit_logs t),
  'background_operation_requests', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.background_operation_requests t),
  'behavior_key_scores', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.behavior_key_scores t),
  'behavior_scores', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.behavior_scores t),
  'config_behavior_pillars', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.config_behavior_pillars t),
  'config_leverage_indicators', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.config_leverage_indicators t),
  'daily_reports', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.daily_reports t),
  'error_logs', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.error_logs t),
  'feedback_360_items', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.feedback_360_items t),
  'feedback_360_responses', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.feedback_360_responses t),
  'job_positions', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.job_positions t),
  'kpi_entries', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.kpi_entries t),
  'kpi_rollup_mappings', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.kpi_rollup_mappings t),
  'kpi_template_target_histories', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.kpi_template_target_histories t),
  'kpi_template_target_history_rollup_children', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.kpi_template_target_history_rollup_children t),
  'kpi_templates', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.kpi_templates t),
  'leverage_scores', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.leverage_scores t),
  'notifications', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.notifications t),
  'organization_revenue_targets', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.organization_revenue_targets t),
  'organizations', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.organizations t),
  'push_subscriptions', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.push_subscriptions t),
  'quarterly_reviews', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.quarterly_reviews t),
  'report_entries', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.report_entries t),
  'review_assignments', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.review_assignments t),
  'ro_kpi_profiles', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.ro_kpi_profiles t),
  'role_access_config', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.role_access_config t),
  'scorecard_checkpoints', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.scorecard_checkpoints t),
  'scorecards', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.scorecards t),
  'shared_kpi_actuals', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.shared_kpi_actuals t),
  'shared_kpi_entries', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.shared_kpi_entries t),
  'shared_kpis', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.shared_kpis t),
  'users', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.users t),
  'weekly_pulses', (SELECT coalesce(json_agg(row_to_json(t)), '[]'::json) FROM public.weekly_pulses t)
) AS snapshot;
