-- Enable RLS on tenant-scoped tables (G4a).

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE ontology_objects ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingestion_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE lineage_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE rule_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
